COMMON: &common
  DEBUG: False
  TESTING: False
  # Base
  SECRET_KEY: YouShouldNeverGuessWithIt
  # Database
  SQLALCHEMY_TRACK_MODIFICATIONS: True
  # Logger
  LOGGER_ENABLED: True
  LOGGER_LEVEL: DEBUG
  LOGGER_FORMAT: '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
  LOGGER_DATE_FORMAT: '%m-%d %H:%M:%S'
  # Babel
  BABEL_DEFAULT_LOCALE: zh_Hans_CN
  # Security
  SECURITY_PASSWORD_HASH: pbkdf2_sha512
  SECURITY_URL_PREFIX: '/accounts'
  SECURITY_PASSWORD_SALT: 6e95b1ed-a8c3-4da0-8bac-6fcb11c39ab4
  SECURITY_EMAIL_SENDER: noreply@localhost
  SECURITY_REGISTERABLE: False
  SECURITY_CHANGEABLE: True
  SECURITY_RECOVERABLE: True
  SECURITY_TRACKABLE: True

  SECURITY_SEND_REGISTER_EMAIL: False
  SECURITY_LOGIN_WITHOUT_CONFIRMATION: True
  SECURITY_SEND_PASSWORD_CHANGE_EMAIL: False
  SECURITY_SEND_PASSWORD_RESET_NOTICE_EMAIL: False

  SECURITY_LOGIN_USER_TEMPLATE: security/extended_login_user.html
  SECURITY_CHANGE_PASSWORD_TEMPLATE: security/extended_change_password.html



DEVELOPMENT: &development
  <<: *common
  DEBUG: True

PRODUCTION: &production
  <<: *common
  DEBUG: False
  TESTING: False

TESTING: &testing
  <<: *common
  TESTING: True